config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#home'

  get 'about', to: 'pages#about'
  
  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :articles
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  
  validates :title, 
            presence: true, 
            length: { minimum: 3, maximum: 50 }

  validates :description, 
            presence: true, 
            length: { minimum: 10, maximum: 300 }
  
  validates :user_id,
            presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  
  validates :name, 
    presence: true,
    uniqueness: true,
    length: { minimum: 3, maximum: 25 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  
  validates :username, 
            presence: true, 
            uniqueness:  true, 
            length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true,
            uniqueness: true,
            length: { maximum: 100 },
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = "You can only edit or delete your articles"
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to categories_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end 

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_user.admin?)
      flash[:danger] = "Only admin can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Successfully loged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Wrong credential!"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Alpha Blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user has been deleted"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end
  
  def require_same_user
    if logged_in? && current_user != @user && !current_user.admin?
      flash[:danger] = "You can only edit or delete your account"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row my-2">
    <div class="col-sm-12">
      <div class="card bg-light p-3">
        <div class="card-title font-weight-bold h3">
          <%= link_to article.title, article_path(article) %>         
        </div>
        <div class="card-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small>
              Created by: <%= article.user.username if article.user %>, 
              <%= time_ago_in_words(article.created_at) %> ago, 
              last updated: <%= time_ago_in_words(article.updated_at) %> 
            </small>
          </div>
        </div>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <% if article.categories.any? %>
            <p>Categories: <%= render article.categories %></p>
          <% end %>
          <div class="article-actions">
            <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %> 
            <%= link_to "Delete this article", article_path(article), method: :delete, 
              data: { confirm: "Are you sure?"}, 
              class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-10">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: "true" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-10">
          <%= f.text_area :description, row: 20, class: "form-control", placeholder: "Description" %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="form-check form-check-inline">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %> 
              <% cb.label(class: "form-check-label mr-2") { cb.check_box(class: "form-check-input") + cb.text } %>
            <% end %>        
          </div>
        </div>        
      </div>
      <div class="form-group">
        <div class="col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg" %>        
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [<%= link_to "Cancel and return to articles listing", articles_path %>]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>

<%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "d-flex justify-content-center") %>
<%= render 'article', obj: @articles %>
<%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "mt-4 d-flex justify-content-center") %>

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>

<div class="card col-sm-12 bg-light p-3">
  <% if @article.user %>
    <ul class="list-unstyled text-center">
      <div class="row justify-content-center">
        <div class="col-md-4 bg-light">
          <li>Created by:</li>
          <li class="my-2"><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
          <li class="article-title">
            <%= link_to @article.user.username, user_path(@article.user) %>
          </li>
          <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <div class="text-center"><strong>Description</strong></div>
  <hr>
  <%= simple_format(@article.description) %>
  <% if @article.categories.any? %>
    <p>Categories: <%= render @article.categories %></p>
  <% end %>
  <div class="article-actions">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
      <%= link_to "Delete this article", article_path(@article), method: :delete, 
        data: { confirm: "Are you sure?"}, 
        class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/categories/_category.html.erb
<span>
  <%= link_to category.name, category_path(category), 
    class: "bg-secondary rounded text-white text-uppercase font-weight-bold p-1" 
  %>
  &nbsp;
</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :name %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: "true" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10">
      <%= f.submit class: "btn btn-primary btn-lg" %>        
    </div>
  </div>
<% end %>

<div class="col-xs-4 col-xs-offset-4">
  [<%= link_to "Cancel and return to categories listing", categories_path %>]
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category Name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Listing all categories</h1>

<%= will_paginate(@categories, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "d-flex justify-content-center") %>
<% @categories.each do |category| %>
  <div class="row my-3 justify-content-center">    
    <div class="col-md-4">
      <div class="card bg-light p-3 text-center">
        <div class="card-title font-weight-bold h3 text-center">
          <%= link_to category.name, category_path(category) %>
        </div>
        <small><%= pluralize(category.articles.count, "articles") %></small>
      </div>
    </div>
  </div>
<% end %>
<%= will_paginate(@categories, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "mt-4 d-flex justify-content-center") %>

app/views/categories/new.html.erb
<h1 align="center">Create New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center">
  <%= "Category: " + @category.name %>
</h1>

<% if logged_in? && current_user.admin? %>
  <div align="center" class="mt-3 mb-4">
    <%= link_to "Edit Category", edit_category_path(@category), 
      class: "bg-primary rounded text-white font-weight-bold p-1" 
    %>
  </div>
<% end %>

<%= will_paginate(@category_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "d-flex justify-content-center") %>
<%= render 'articles/article', obj: @category_articles %>
<%= will_paginate(@category_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "mt-4 d-flex justify-content-center") %>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; by Xu
    </small>
    <nav>
      <ul>
        <li><%= link_to 'About', about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row justify-content-center mt-3">
  <div class="col-sm-8">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%="#{name}"%> alert-dismissible show fade" role="alert">
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <%= link_to 'Alpha Blog', root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
      aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-between" id="collapsibleNavId">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <%= link_to 'Articles', articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Users', users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
        <ul class="dropdown-menu" aria-labelledby="dropdownId">
          <li><%= link_to 'All categories', categories_path, class: "dropdown-item" %></li>
          <% Category.all.each do |category| %>
            <li><%= link_to "#{category.name}", category_path(category), class: "dropdown-item" %></li>
          <% end %>
          <% if logged_in? && current_user.admin? %>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Create new category', new_category_path, class: "dropdown-item" %></li>          
          <% end %>
        </ul>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Actions</a>
          <ul class="dropdown-menu" aria-labelledby="dropdownId">
            <li><%= link_to 'New article', new_article_path, class: "dropdown-item" %></li>            
          </ul>
        </li>
      <% end %>
    </ul>

    <ul class="navbar-nav mt-2 mt-lg-0">
      <% if logged_in? %>        
        <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin? %></a>
          <ul class="dropdown-menu" aria-labelledby="dropdownId">
            <%= link_to 'View your profile', user_path(current_user), class: "dropdown-item" %>
            <%= link_to 'Edit your profile', edit_user_path(current_user), class: "dropdown-item" %>
          </ul>
        </li>
        <li class="nav-item active">
          <%= link_to 'Log Out', logout_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to 'Log In', login_path, class: "nav-link" %>        
        </li>
        <li class="nav-item active">
          <%= link_to 'Sign Up', signup_path, class: "nav-link" %>        
        </li>
      <% end %>  
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container mt-4">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <br>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is about page</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
  <h1 class="mt-5">ALPHA BLOG</h1>
  <%= link_to 'Sign up now', signup_path, class: "btn btn-info btn-lg btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row justify-content-center">
    <div class="col-sm-8">
      <div class="card text-white bg-danger border-danger p-3">
        <div class="card-heading">
          <h2 class="card-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being saved:
          </h2>
        </div>
        <div class="card-body">
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-10">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: "true" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-10">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password %>
        </div>
        <div class="col-sm-10">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-10">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-primary btn-lg") %>        
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [<%= link_to "Cancel and return to articles listing", articles_path %>]
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Alpha Bloggers</h1>

<%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "d-flex justify-content-center") %>
<% @users.each do |user| %>
  <ul class="list-unstyled text-center mt-3">
    <div class="row justify-content-center">
      <div class="card col-md-4 bg-light py-3">
        <li class="mb-2"><%= link_to gravatar_for(user), user_path(user) %></li>
        <li class="article-title">
          <%= link_to user.username, user_path(user) %>
        </li>
        <li>
          <small><%= pluralize(user.articles.count, "article") if user.articles %></small>
        </li>
        <% if logged_in? && current_user.admin? %>
          <li>
            <%= link_to 'Delete this user', user_path(user), method: :delete, 
              data: {confirm: "Are you sure want to delete this user and all their articles?"}, 
              class: "btn btn-xs btn-danger" 
            %>
          </li>
        <% end %>
      </div>
    </div>
  </ul>
<% end %>
<%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "mt-4 d-flex justify-content-center") %>

app/views/users/new.html.erb
<h1 align="center">Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>

<div class="row justify-content-center">
  <div class="col-md-4 text-center my-3">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>

<h4 align="center"><%= @user.username %>'s articles</h4>

<%= will_paginate(@user_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "d-flex justify-content-center") %>
<%= render 'articles/article', obj: @user_articles %>
<%= will_paginate(@user_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer, class: "mt-4 d-flex justify-content-center") %>